### ISSUE TITLE
Just a question 

### ISSUE THREAD

**Issue by chrisfal10** [yezz123/Phisher#11]
Any tools to send the link as email with the templates?

**Comment by yezz123** [comment]
you can use a short link provider and send the phishing link in an email template.
- like if you know the person in a good way try to create a template for an email that can make him interests ex. a person that loves cats create an email template with a cat's subject then generate the template with Phisher and use a Service like [app.bitly](https://app.bitly.com/bbt2/) then send it with the email and you can wait for the response. 📧
