### ISSUE TITLE
Link from the phisher dosen't work on other wifi servers

### ISSUE THREAD

**Issue by MrRobotAlex** [yezz123/Phisher#14]
Let's say i try to hack myself  , well i open kail terminal and then there is no link .So i go to 127.0.0.1:4040/stas to get it .
Ok i opened my phone and use mobile data(not the wifi where the ngrok server was created) and when i use the link he says "ERR_NGROK_3200"

**Comment by yezz123** [comment]
@MrRobotAlex check your connection or the way how you create this also if you can drop the log
