### ISSUE TITLE
No Link to Copy

### ISSUE THREAD

**Issue by shittyfollower** [yezz123/Phisher#4]
Hey,
It doesn't generate a link I can copy after indicating what service to try (1,2,3 etc).
What component does it require to generate the links, other than the requirements?
Thanks

**Comment by OneParsec** [comment]
Can you send a screenshots?

**Comment by yezz123** [comment]
@shittyfollower Thank you for reporting !
I can't told you now what to do give me more information where you work with it (debian / termux or ....).

**Comment by yezz123** [comment]
I check the code and all the repository still work please when the link want be generated .
Go to this link **Ngrok's Stat** :
```
http://127.0.0.1:4040/status
```
Then copy the Https link and send it to the victim.
And thank you for Reporting the issue! ✌
Stay Safe 🙏

**Comment by nosa999** [comment]
> ```
> http://127.0.0.1:4040/status
> ```

Hi,
http://127.0.0.1:4040/status isn't available now.
![image](https://user-images.githubusercontent.com/40929193/107109845-afc0f000-6858-11eb-9712-3870cdbe1d84.png)

**Comment by nosa999** [comment]
> I check the code and all the repository still work please when the link want be generated .
> Go to this link **Ngrok's Stat** :
> 
> ```
> http://127.0.0.1:4040/status
> ```
> 
> Then copy the Https link and send it to the victim.
> And thank you for Reporting the issue! ✌
> Stay Safe 🙏

Hi,
http://127.0.0.1:4040/status isn't available now.
![image](https://user-images.githubusercontent.com/40929193/107109909-f7477c00-6858-11eb-82f5-527fcefd641f.png)

**Comment by yezz123** [comment]
Hy! @nosa999 
I guess the ngrok Runner didn't install and that don't give you authority to the `127.0.0.1:4040/status`.
So you will do it Manually!
go to Official Ngrok website `https://ngrok.com/download` the download the zip file then extract the Runner, then copy it to Phisher directory and run `bash Phisher.sh`.

https://user-images.githubusercontent.com/52716203/107113309-7b503280-685e-11eb-8894-0c24caaad495.mp4

This is a video that the repository and the Phisher still work.
Stay Safe & happy Phishing! 💯

**Comment by Progluver** [comment]
@yezz123 now it is fixed. You can check #9
